#!/bin/sh
set -e
export -n CDPATH

# Globally used functions

escape_quotes() {
  for line in "$@"; do
    line=$(echo "$line" | sed -e "s/\\([\"\]\\)/\\\\\\1/g")
    echo "\"""$line""\""
  done
}

# Parse region specification

if [ "$1" = "--region" ]; then
  shift
  export FIRE_REGION="$1"
  shift
fi

# Set up global variables

export FIRE_REGION=${FIRE_REGION:=$(aws configure get region)}
export FIRE_PROJECT=${FIRE_PROJECT:="project"}
export FIRE_PROGRAM_NAME=${FIRE_PROGRAM_NAME:="fire-manager"}
export FIRE_ENVIRONMENT=${FIRE_ENVIRONMENT:="development"}
export FIRE_PUBLIC_KEY_FILE=${FIRE_PUBLIC_KEY_FILE}
export FIRE_NAME="${FIRE_PROJECT}:${FIRE_PROGRAM_NAME}"

# Set up cache (temporary files) directory

MKTEMP=$(command -v gmktemp mktemp | head -1)
if [ -z "$MKTEMP" ]; then
  echo "mktemp could not be found. Please install GNU coreutils." >&2
  exit 1
fi

if [ -z "$FIRE_CACHE_DIR" ]; then
  export FIRE_TEMP_CACHE_DIR=1
  export FIRE_CACHE_DIR
  FIRE_CACHE_DIR="$(mktemp -d)"
  trap 'rm -rf $FIRE_CACHE_DIR' 0 2 3 15
else
  trap 'rm -f $FIRE_CACHE_DIR/*' 0 2 3 15
fi

READLINK=$(command -v greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "readlink could not be found. Please install GNU coreutils." >&2
  exit 1
fi

export BIN_PATH
BIN_PATH="$($READLINK -f "$0" | xargs dirname)"

export LOAD_SHARED_PATH="${BIN_PATH}/shared/load-shared"
export PATH="${BIN_PATH}:${PATH}"

case "$1" in
  "" | "-h" | "--help" )
    echo "Help not implemented yet"
    ;;
  * )
    command_path="$(command -v "fire-${1}" || true)"
    if [ "$command_path" = "" ]; then
      unset command_path
    fi
    if [ -n "${command_path+x}" ]; then
      shift 1
      eval "$command_path" "$@"
    fi
esac
