#!/bin/sh
set -e

. "$LOAD_SHARED_PATH"

load_shared functions

display_var() {
  eval "echo \"$1\": \$$1"
}

printf "Displaying information about region %s" "$FIRE_REGION"
echo

# shellcheck disable=SC2034
# These variables are used in the eval inside display_var
{
  VPC_ID="$(get_vpc_info vpc_id)"
  display_var VPC_ID
  SUBNET_ID="$(get_subnet_info subnet_id)"
  display_var SUBNET_ID
  SECURITY_GROUP="$(get_security_group_info group_id)"
  display_var SECURITY_GROUP
  INTERNET_GATEWAY_ID="$(get_internet_gateway_info internet_gateway_id)"
  display_var INTERNET_GATEWAY_ID
  ROUTE_TABLE="$(get_route_table_info route_table_id)"
  display_var ROUTE_TABLE
  IPV4_CIDR_BLOCKS="$(get_route_table_info ipv4_cidr_blocks)"
  display_var IPV4_CIDR_BLOCKS
  IPV6_CIDR_BLOCKS="$(get_route_table_info ipv6_cidr_blocks)"
  display_var IPV6_CIDR_BLOCKS
  ASSOCIATION_IDS="$(get_route_table_info association_ids)"
  display_var ASSOCIATION_IDS
  KEY_PAIR="$(get_key_pair_info key_name)"
  display_var KEY_PAIR
  BASE_INSTANCE="$(get_base_instance_info instance_id)"
  display_var BASE_INSTANCE
  INSTANCE_IP="$(get_base_instance_info public_ip)"
  display_var INSTANCE_IP
}
